# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/k.oliinyk/prplMesh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/k.oliinyk/prplMesh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/k.oliinyk/prplMesh/CMakeFiles /home/k.oliinyk/prplMesh/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/k.oliinyk/prplMesh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest-build/googletest/CMakeFiles/gtest.dir/build.make googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named bpl

# Build rule for target.
bpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpl
.PHONY : bpl

# fast build rule for target.
bpl/fast:
	$(MAKE) -f framework/platform/bpl/CMakeFiles/bpl.dir/build.make framework/platform/bpl/CMakeFiles/bpl.dir/build
.PHONY : bpl/fast

#=============================================================================
# Target rules for targets named bpl_test

# Build rule for target.
bpl_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpl_test
.PHONY : bpl_test

# fast build rule for target.
bpl_test/fast:
	$(MAKE) -f framework/platform/bpl/test/CMakeFiles/bpl_test.dir/build.make framework/platform/bpl/test/CMakeFiles/bpl_test.dir/build
.PHONY : bpl_test/fast

#=============================================================================
# Target rules for targets named nbapi

# Build rule for target.
nbapi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nbapi
.PHONY : nbapi

# fast build rule for target.
nbapi/fast:
	$(MAKE) -f framework/platform/nbapi/CMakeFiles/nbapi.dir/build.make framework/platform/nbapi/CMakeFiles/nbapi.dir/build
.PHONY : nbapi/fast

#=============================================================================
# Target rules for targets named elpp

# Build rule for target.
elpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elpp
.PHONY : elpp

# fast build rule for target.
elpp/fast:
	$(MAKE) -f framework/external/easylogging/CMakeFiles/elpp.dir/build.make framework/external/easylogging/CMakeFiles/elpp.dir/build
.PHONY : elpp/fast

#=============================================================================
# Target rules for targets named tlvf

# Build rule for target.
tlvf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tlvf
.PHONY : tlvf

# fast build rule for target.
tlvf/fast:
	$(MAKE) -f framework/tlvf/CMakeFiles/tlvf.dir/build.make framework/tlvf/CMakeFiles/tlvf.dir/build
.PHONY : tlvf/fast

#=============================================================================
# Target rules for targets named tlvf_test

# Build rule for target.
tlvf_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tlvf_test
.PHONY : tlvf_test

# fast build rule for target.
tlvf_test/fast:
	$(MAKE) -f framework/tlvf/test/CMakeFiles/tlvf_test.dir/build.make framework/tlvf/test/CMakeFiles/tlvf_test.dir/build
.PHONY : tlvf_test/fast

#=============================================================================
# Target rules for targets named mapfcommon

# Build rule for target.
mapfcommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapfcommon
.PHONY : mapfcommon

# fast build rule for target.
mapfcommon/fast:
	$(MAKE) -f framework/common/CMakeFiles/mapfcommon.dir/build.make framework/common/CMakeFiles/mapfcommon.dir/build
.PHONY : mapfcommon/fast

#=============================================================================
# Target rules for targets named mapf_common_encryption_tests

# Build rule for target.
mapf_common_encryption_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapf_common_encryption_tests
.PHONY : mapf_common_encryption_tests

# fast build rule for target.
mapf_common_encryption_tests/fast:
	$(MAKE) -f framework/common/test/CMakeFiles/mapf_common_encryption_tests.dir/build.make framework/common/test/CMakeFiles/mapf_common_encryption_tests.dir/build
.PHONY : mapf_common_encryption_tests/fast

#=============================================================================
# Target rules for targets named ieee1905_transport_messages

# Build rule for target.
ieee1905_transport_messages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ieee1905_transport_messages
.PHONY : ieee1905_transport_messages

# fast build rule for target.
ieee1905_transport_messages/fast:
	$(MAKE) -f framework/transport/ieee1905_transport/CMakeFiles/ieee1905_transport_messages.dir/build.make framework/transport/ieee1905_transport/CMakeFiles/ieee1905_transport_messages.dir/build
.PHONY : ieee1905_transport_messages/fast

#=============================================================================
# Target rules for targets named ieee1905_transport

# Build rule for target.
ieee1905_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ieee1905_transport
.PHONY : ieee1905_transport

# fast build rule for target.
ieee1905_transport/fast:
	$(MAKE) -f framework/transport/ieee1905_transport/CMakeFiles/ieee1905_transport.dir/build.make framework/transport/ieee1905_transport/CMakeFiles/ieee1905_transport.dir/build
.PHONY : ieee1905_transport/fast

#=============================================================================
# Target rules for targets named ieee1905_transport_lib

# Build rule for target.
ieee1905_transport_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ieee1905_transport_lib
.PHONY : ieee1905_transport_lib

# fast build rule for target.
ieee1905_transport_lib/fast:
	$(MAKE) -f framework/transport/ieee1905_transport/CMakeFiles/ieee1905_transport_lib.dir/build.make framework/transport/ieee1905_transport/CMakeFiles/ieee1905_transport_lib.dir/build
.PHONY : ieee1905_transport_lib/fast

#=============================================================================
# Target rules for targets named ieee1905_transport_broker_tests

# Build rule for target.
ieee1905_transport_broker_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ieee1905_transport_broker_tests
.PHONY : ieee1905_transport_broker_tests

# fast build rule for target.
ieee1905_transport_broker_tests/fast:
	$(MAKE) -f framework/transport/ieee1905_transport/test/CMakeFiles/ieee1905_transport_broker_tests.dir/build.make framework/transport/ieee1905_transport/test/CMakeFiles/ieee1905_transport_broker_tests.dir/build
.PHONY : ieee1905_transport_broker_tests/fast

#=============================================================================
# Target rules for targets named bcl_unit_tests

# Build rule for target.
bcl_unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bcl_unit_tests
.PHONY : bcl_unit_tests

# fast build rule for target.
bcl_unit_tests/fast:
	$(MAKE) -f common/beerocks/bcl/CMakeFiles/bcl_unit_tests.dir/build.make common/beerocks/bcl/CMakeFiles/bcl_unit_tests.dir/build
.PHONY : bcl_unit_tests/fast

#=============================================================================
# Target rules for targets named bcl

# Build rule for target.
bcl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bcl
.PHONY : bcl

# fast build rule for target.
bcl/fast:
	$(MAKE) -f common/beerocks/bcl/CMakeFiles/bcl.dir/build.make common/beerocks/bcl/CMakeFiles/bcl.dir/build
.PHONY : bcl/fast

#=============================================================================
# Target rules for targets named btl

# Build rule for target.
btl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 btl
.PHONY : btl

# fast build rule for target.
btl/fast:
	$(MAKE) -f common/beerocks/btl/CMakeFiles/btl.dir/build.make common/beerocks/btl/CMakeFiles/btl.dir/build
.PHONY : btl/fast

#=============================================================================
# Target rules for targets named bwl_dummy_unit_tests

# Build rule for target.
bwl_dummy_unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bwl_dummy_unit_tests
.PHONY : bwl_dummy_unit_tests

# fast build rule for target.
bwl_dummy_unit_tests/fast:
	$(MAKE) -f common/beerocks/bwl/CMakeFiles/bwl_dummy_unit_tests.dir/build.make common/beerocks/bwl/CMakeFiles/bwl_dummy_unit_tests.dir/build
.PHONY : bwl_dummy_unit_tests/fast

#=============================================================================
# Target rules for targets named bwl

# Build rule for target.
bwl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bwl
.PHONY : bwl

# fast build rule for target.
bwl/fast:
	$(MAKE) -f common/beerocks/bwl/CMakeFiles/bwl.dir/build.make common/beerocks/bwl/CMakeFiles/bwl.dir/build
.PHONY : bwl/fast

#=============================================================================
# Target rules for targets named prplmesh_hostapd

# Build rule for target.
prplmesh_hostapd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prplmesh_hostapd
.PHONY : prplmesh_hostapd

# fast build rule for target.
prplmesh_hostapd/fast:
	$(MAKE) -f common/beerocks/hostapd/CMakeFiles/prplmesh_hostapd.dir/build.make common/beerocks/hostapd/CMakeFiles/prplmesh_hostapd.dir/build
.PHONY : prplmesh_hostapd/fast

#=============================================================================
# Target rules for targets named prplmesh_hostapd_unit_tests

# Build rule for target.
prplmesh_hostapd_unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prplmesh_hostapd_unit_tests
.PHONY : prplmesh_hostapd_unit_tests

# fast build rule for target.
prplmesh_hostapd_unit_tests/fast:
	$(MAKE) -f common/beerocks/hostapd/CMakeFiles/prplmesh_hostapd_unit_tests.dir/build.make common/beerocks/hostapd/CMakeFiles/prplmesh_hostapd_unit_tests.dir/build
.PHONY : prplmesh_hostapd_unit_tests/fast

#=============================================================================
# Target rules for targets named btlvf

# Build rule for target.
btlvf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 btlvf
.PHONY : btlvf

# fast build rule for target.
btlvf/fast:
	$(MAKE) -f common/beerocks/tlvf/CMakeFiles/btlvf.dir/build.make common/beerocks/tlvf/CMakeFiles/btlvf.dir/build
.PHONY : btlvf/fast

#=============================================================================
# Target rules for targets named beerocks_agent

# Build rule for target.
beerocks_agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beerocks_agent
.PHONY : beerocks_agent

# fast build rule for target.
beerocks_agent/fast:
	$(MAKE) -f agent/src/beerocks/slave/CMakeFiles/beerocks_agent.dir/build.make agent/src/beerocks/slave/CMakeFiles/beerocks_agent.dir/build
.PHONY : beerocks_agent/fast

#=============================================================================
# Target rules for targets named beerocks_agent_unit_tests

# Build rule for target.
beerocks_agent_unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beerocks_agent_unit_tests
.PHONY : beerocks_agent_unit_tests

# fast build rule for target.
beerocks_agent_unit_tests/fast:
	$(MAKE) -f agent/src/beerocks/slave/CMakeFiles/beerocks_agent_unit_tests.dir/build.make agent/src/beerocks/slave/CMakeFiles/beerocks_agent_unit_tests.dir/build
.PHONY : beerocks_agent_unit_tests/fast

#=============================================================================
# Target rules for targets named beerocks_fronthaul

# Build rule for target.
beerocks_fronthaul: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beerocks_fronthaul
.PHONY : beerocks_fronthaul

# fast build rule for target.
beerocks_fronthaul/fast:
	$(MAKE) -f agent/src/beerocks/fronthaul_manager/CMakeFiles/beerocks_fronthaul.dir/build.make agent/src/beerocks/fronthaul_manager/CMakeFiles/beerocks_fronthaul.dir/build
.PHONY : beerocks_fronthaul/fast

#=============================================================================
# Target rules for targets named bml

# Build rule for target.
bml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bml
.PHONY : bml

# fast build rule for target.
bml/fast:
	$(MAKE) -f controller/src/beerocks/bml/CMakeFiles/bml.dir/build.make controller/src/beerocks/bml/CMakeFiles/bml.dir/build
.PHONY : bml/fast

#=============================================================================
# Target rules for targets named beerocks_cli

# Build rule for target.
beerocks_cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beerocks_cli
.PHONY : beerocks_cli

# fast build rule for target.
beerocks_cli/fast:
	$(MAKE) -f controller/src/beerocks/cli/CMakeFiles/beerocks_cli.dir/build.make controller/src/beerocks/cli/CMakeFiles/beerocks_cli.dir/build
.PHONY : beerocks_cli/fast

#=============================================================================
# Target rules for targets named beerocks_controller

# Build rule for target.
beerocks_controller: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beerocks_controller
.PHONY : beerocks_controller

# fast build rule for target.
beerocks_controller/fast:
	$(MAKE) -f controller/src/beerocks/master/CMakeFiles/beerocks_controller.dir/build.make controller/src/beerocks/master/CMakeFiles/beerocks_controller.dir/build
.PHONY : beerocks_controller/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... bpl"
	@echo "... bpl_test"
	@echo "... nbapi"
	@echo "... elpp"
	@echo "... tlvf"
	@echo "... tlvf_test"
	@echo "... mapfcommon"
	@echo "... mapf_common_encryption_tests"
	@echo "... ieee1905_transport_messages"
	@echo "... ieee1905_transport"
	@echo "... ieee1905_transport_lib"
	@echo "... ieee1905_transport_broker_tests"
	@echo "... bcl_unit_tests"
	@echo "... bcl"
	@echo "... btl"
	@echo "... bwl_dummy_unit_tests"
	@echo "... bwl"
	@echo "... prplmesh_hostapd"
	@echo "... prplmesh_hostapd_unit_tests"
	@echo "... btlvf"
	@echo "... beerocks_agent"
	@echo "... beerocks_agent_unit_tests"
	@echo "... beerocks_fronthaul"
	@echo "... bml"
	@echo "... beerocks_cli"
	@echo "... beerocks_controller"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

