#
---
_namespace: wfa_map

tlvAssociatedStaMldConfigurationReport:
 _type: class
 _is_tlv_class : True
 type:
  _type: eTlvTypeMap
  _value_const: TLV_ASSOCIATED_STA_MLD_CONFIGURATION_REPORT
 length: uint16_t
 sta_mld_mac_addr: sMacAddr
 ap_mld_mac_addr: sMacAddr
 flags: sFlags
 reserved:
  _type: uint8_t
  _length: [18]
 num_affliated_sta_length:
  _type: uint8_t
  _length_var: True
 affliated_sta:
  _type: cAffliatedsta
  _length: [num_affliated_sta_length]
 
sFlags:
 _type: struct
 _bit_field: uint8_t
 str_mode:
  _bit_range: [7,7]
 nstr_mode:
  _bit_range: [6,6]
 emlsr_mode:
  _bit_range: [5,5]
 emlmr_mode:
  _bit_range: [4,4]
 reserved:
  _bit_range: [3,0]

cAffliatedsta:
 _type: class
 bssid: sMacAddr
 affliated_sta_mac_addr: sMacAddr
 reserved:
  _type: uint8_t
  _length: [19]

