---
_namespace: wfa_map

tlvAgentApMLDconfiguration:
  _type: class
  _is_tlv_class: true
  type:
    _type: eTlvTypeMap
    _value_const: TLV_AGENT_AP_MLD_CONFIGURATION
  length: uint16_t
  num_ap_mld:
    _type: uint8_t
    _length_var: true
  ap_mld_entries:
    _type: cAPMLDEntry
    _length: [num_ap_mld]

cAPMLDEntry:
  _type: class
  flags: sFlags1
  ssid_length:
    _type: uint8_t
    _length_var: true
  ssid:
    _type: char
    _length: [ssid_length]
  ap_mld_mac_addr: sMacAddr
  flags: sFlags2
  reserved: 
    _type: uint8_t
    _length: [20]
  num_affiliated_ap:
    _type: uint8_t
    _length_var: true
  affiliated_ap_entries:
    _type: cAffiliatedAPEntry
    _length: [num_affiliated_ap]

sFlags1:
  _type: struct
  _bit_field: uint8_t
  ap_mld_mac_addr_valid:
    _bit_range: [7, 7]
    _comment: 0 = Not Valid, 1 = Valid
  reserved:
    _bit_range: [6, 0]

sFlags2:
  _type: struct
  _bit_field: uint8_t
  str:
    _bit_range: [7, 7]
    _comment: 0 = Disabled, 1 = Enabled
  nstr:
    _bit_range: [6, 6]
    _comment: 0 = Disabled, 1 = Enabled
  emlsr:
    _bit_range: [5, 5]
    _comment: 0 = Disabled, 1 = Enabled
  emlmr:
    _bit_range: [4, 4]
    _comment: 0 = Disabled, 1 = Enabled
  reserved:
    _bit_range: [3, 0]

cAffiliatedAPEntry:
  _type: class
  flags: sFlags3
  ruid: sMacAddr
  affiliated_ap_mac_addr: sMacAddr
  link_id:
    _type: uint8_t
    _comment: 0-15 = Variable, 16-255 = Reserved
  reserved:
    _type: uint8_t
    _length: [18]

sFlags3:
  _type: struct
  _bit_field: uint8_t
  affiliated_ap_mac_addr_valid:
    _bit_range: [7, 7]
    _comment: 0 = Not valid, 1 = Valid
  link_id_valid:
    _bit_range: [6, 6]
    _comment: 0 = Not valid, 1 = Valid
  reserved:
    _bit_range: [5, 0]
