#
---
_namespace: wfa_map

tlvBssConfigurationResponse:
  _type: class
  _is_tlv_class : True
  type:
    _type: eTlvTypeMap
    _value_const: TLV_BSS_CONFIGURATION_RESPONSE
  length: uint16_t
  dpp_configuration_object:
    _type: uint8_t
    _length: []
    _comment: |
      One or more JSON encoded DPP Configuration Object attributes (See section 8.1 of Wi-Fi Easy
      Connect Specification).
