FROM alpine:3.12

RUN apk add --update --no-cache \
    autoconf \
    binutils \
    bridge-utils \
    cmake \
    curl \
    gcc \
    g++ \
    git \
    json-c-dev \
    libnl3-dev \
    libtool \
    musl-dev \
    zeromq-dev \
    linux-headers \
    make \
    ninja \
    openssl-dev \
    pkgconf \
    py3-yaml \
    python3 \
    sed \
    clang-extra-tools
