#! /bin/sh
###############################################################
# SPDX-License-Identifier: BSD-2-Clause-Patent
# SPDX-FileCopyrightText: 2020 the prplMesh contributors (see AUTHORS.md)
# This code is subject to the terms of the BSD+Patent license.
# See LICENSE file for more details.
###############################################################
# Inspired on https://coolaj86.com/articles/vanilla-devops-git-credentials-cheatsheet/

echo $RDK_GIT_TOKEN
