- name: feed_intel
  uri: https://gitlab.com/prpl-foundation/prplwrt/feed-intel.git
  tracking_branch: ugw-8.4.2-cleanup
  revision: 735c53bf0c8089eefffdd17017c7338386534d6b
- name: feed_prpl
  uri: https://gitlab.com/prpl-foundation/prplwrt/feed-prpl.git
  tracking_branch: prpl-19.07
  revision: 52c3f0a7f7d220401fbf08d4bcf59908cf3c3d35
- name: sah
  uri: https://gitlab.com/soft.at.home/buildsystems/openwrt/sah-packages.git
  tracking_branch: master
  revision: 3c8fef0f760b26d3c54cc518dd71f6bc5f79680a
