feeds:
  - name: sah
    uri: https://gitlab.com/soft.at.home/buildsystems/openwrt/sah-packages.git
    tracking_branch: master
    revision: 553475f301edad072ac0cfeb11d1abe32569fe7d

packages:
  - libamxb
  - libamxc
  - libamxd
  - libamxj
  - libamxo
  - libamxp
  - uriparser
  - yajl
  - amxb-ubus
  - amxo-cg
