###############################################################
# SPDX-License-Identifier: BSD-2-Clause-Patent
# SPDX-FileCopyrightText: 2019-2020 the prplMesh contributors (see AUTHORS.md)
# This code is subject to the terms of the BSD+Patent license.
# See LICENSE file for more details.
###############################################################

variables:
  PACKAGE_REGISTRY_BASE_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"
  TURRIS_OMNIA_FULLIMAGE: "openwrt-mvebu-cortexa9-cznic_turris-omnia-sysupgrade.img.gz"
  GLINET_B1300_FULLIMAGE: "openwrt-ipq40xx-generic-glinet_gl-b1300-squashfs-sysupgrade.bin"
  AXEPOINT_FULLIMAGE: "AX3000_1600_ETH_11AXUCI-squashfs-fullimage.img"
  NEC_WX3000HP_FULLIMAGE: "AX3000_1600_ETH_11AXUCI_ASURADA-squashfs-fullimage.img"
  TURRIS_OMNIA_RDKB_FULLIMAGE: "rdkb-generic-broadband-image_turris-omnia.rootfs.tar.gz"
  HAZE_FULLIMAGE: "openwrt-ipq807x-generic-prpl_haze-squashfs-sysupgrade.bin"
  URX_OSP_FULLIMAGE: "openwrt-intel_x86-lgm-PRPL_OSP_TB341-osp_tb341_fullimage.img"
  OSP_PACKAGE_ID: 13754300

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'

stages:
  - build
  - test
  - certification-R1-haze
  - certification-R1-turris-omnia
  - certification-R1-glinet
  - certification-R1-axepoint
  - certification-R4-OSP
  - certification-R4-haze
  - certification-R4-turris-omnia
  - certification-R4-axepoint
  - upload
  - release

include:
  - local: "/ci/templates.yml"
  - local: "/ci/certification/templates.yml"

.rules-for-releases: &onrelease
  - if: '$CI_COMMIT_TAG =~ /\A\d+\.\d+\.\d+\z/'

build-for-rdkb-turris-omnia:
  extends: .build-for-rdkb
  variables:
    TARGET_DEVICE: "turris-omnia"
  retry: 2
  rules:
    - when: manual

build-for-turris-omnia-legacy:
  extends: .build-for-openwrt-legacy
  variables:
    TARGET_DEVICE: "turris-omnia"
  rules:
    - when: manual

build-for-glinet-b1300-legacy:
  extends: .build-for-openwrt-legacy
  variables:
    TARGET_DEVICE: "glinet-b1300"
  rules:
    - when: manual

build-for-intel-mips:
  extends: .build-for-openwrt-legacy
  variables:
    TARGET_DEVICE: "intel_mips"
  rules:
    - when: manual

build-for-turris-omnia:
  extends: .build-for-openwrt
  variables:
    TARGET_DEVICE: "turris-omnia"
  rules:
    - when: manual

build-for-glinet-b1300:
  extends: .build-for-openwrt
  variables:
    TARGET_DEVICE: "glinet-b1300"
  rules:
    - when: manual

build-for-haze:
  extends: .build-for-openwrt
  variables:
    TARGET_DEVICE: "haze"
  rules:
    - when: manual

build-for-cgr:
  stage: build
  variables:
    PRPLMESH_REVISION: $CI_COMMIT_SHA
  trigger:
    project: essensium-mind/prplmesh/puma7
    strategy: depend
  needs: []
  rules:
    - if: '$CI_PARENT_PIPELINE_SOURCE == "schedule" && $BUILD_CGR == "yes"'

changelog:
  stage: build
  image: $CI_REGISTRY_IMAGE/prplmesh-scripts:$PARENT_PIPELINE_ID
  rules:
    - if: '$CI_COMMIT_TAG =~ /\A\d+\.\d+\.\d+\z/'
    - when: manual
      allow_failure: true
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: image-build-scripts
  script:
    - tools/gen_changelog.py --latest-version --no-unreleased --no-preamble > CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md
